// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';

export function ApplyUpdateAndRestart():Promise<void>;

export function CheckForUpdates():Promise<updater.Status>;

export function GetAPIBaseURL():Promise<string>;

export function SaveCSV(arg1:string,arg2:string):Promise<string>;

export function Version():Promise<string>;
